grafana:
  adminPassword: Ashraf-password123
  grafana.ini:
    server:
      root_url: http://grafana.lab:8080
    auth.generic_oauth:
      enabled: true
      name: Connexion SSO (Keycloak)
      allow_sign_up: true
      client_id: grafana
      # Le secret devra être récupéré dans Keycloak plus tard. On met un placeholder pour l'instant.
      client_secret: ${KEYCLOAK_GRAFANA_SECRET} 
      scopes: openid profile email roles
      auth_url: http://localhost:8081/realms/homelab/protocol/openid-connect/auth
      # Les URLs internes utilisent le DNS de Kubernetes pour que Grafana parle à Keycloak sans sortir de l'usine
      token_url: http://my-keycloak.keycloak.svc.cluster.local:80/realms/homelab/protocol/openid-connect/token
      api_url: http://my-keycloak.keycloak.svc.cluster.local:80/realms/homelab/protocol/openid-connect/userinfo
      role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
