apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: kuma.lab
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: uptime-kuma-service
            port: 
              number: 80